export const tags = [
  {
    id: 1,
    color: 'dark',
    backgroundColor: '#FFFFFF',
    border: '#8A8A8A',
    description: 'Not evaluated',
    abbreviation: '',
  },
  {
    id: 2,
    color: 'dark',
    backgroundColor: '#D61D07',
    description: 'Critically Endangered',
    abbreviation: 'CR',
  },
  {
    id: 3,
    color: 'dark',
    backgroundColor: '#D1D1C7',
    description: 'Data Deficient',
    abbreviation: 'DD',
  },
  {
    id: 4,
    color: 'dark',
    backgroundColor: '#FC7F3F',
    description: 'Endangered',
    abbreviation: 'EN',
  },
  {
    id: 5,
    color: 'light',
    backgroundColor: '#4C253B',
    description: 'Extinct in the Wild',
    abbreviation: 'EW',
  },
  { id: 6, color: 'light', backgroundColor: '#000000', description: 'Extinct', abbreviation: 'EX' },
  {
    id: 7,
    color: 'dark',
    backgroundColor: '#60C659',
    description: 'Least Concern',
    abbreviation: 'LC',
  },
  {
    id: 8,
    color: 'dark',
    backgroundColor: '#FFFFFF',
    border: '#8A8A8A',
    description: 'Not recognised',
    abbreviation: 'NR',
  },
  {
    id: 9,
    color: 'dark',
    backgroundColor: '#CCE227',
    border: '#8A8A8A',
    description: 'Near Threatened',
    abbreviation: 'NT',
  },
  {
    id: 10,
    color: 'dark',
    backgroundColor: '#FFFFFF',
    border: '#8A8A8A',
    description: 'Under Review',
    abbreviation: 'UR',
  },
  {
    id: 11,
    color: 'dark',
    backgroundColor: '#F9E814',
    description: 'Vulnerable',
    abbreviation: 'VU',
  },
];

export const regions = [
  { id: 'africa', name: 'Africa' },
  { id: 'asia', name: 'Asia' },
  { id: 'europe', name: 'Europe' },
  { id: 'neotropics', name: 'Neotropics' },
  { id: 'northamerica', name: 'North America' },
  { id: 'oceania', name: 'Oceania' },
];
